export const ALL_FORM_REQUEST = 'ALL_FORM_REQUEST'
export const ALL_FORM_FAIL = 'ALL_FORM_FAIL'
export const ALL_FORM_SUCCESS = 'ALL_FORM_SUCCESS'

export const NEW_FORM_REQUEST = 'NEW_FORM_REQUEST'
export const NEW_FORM_FAIL = 'NEW_FORM_FAIL'
export const NEW_FORM_SUCCESS = 'NEW_FORM_SUCCESS'


export const LABALE_CHANGE = 'LABEL_CHANGE'
export const CHANGE_INPUT_PLACEHOLDER = 'CHANGE_INPUT_PLACEHOLDER'


export const CHANGE_CHECKBOX_LABLE = 'CHANGE_CHECKBOX_LABLE'
export const CHANGE_CHECKBOX_REQUIRED = 'CHANGE_CHECKBOX_REQUIRED'
export const CHANGE_CHECKBOX_TITLE = 'CHANGE_CHECKBOX_TITLE'

export const SET_PREVIOUS_FORM = "SET_PREVIOUS_FORM"