export const ALL_FORM_REQUEST = 'ALL_FORM_REQUEST'
export const ALL_FORM_FAIL = 'ALL_FORM_FAIL'
export const ALL_FORM_SUCCESS = 'ALL_FORM_SUCCESS'

export const NEW_FORM_REQUEST = 'NEW_FORM_REQUEST'
export const NEW_FORM_FAIL = 'NEW_FORM_FAIL'
export const NEW_FORM_SUCCESS = 'NEW_FORM_SUCCESS'