export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST"
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS"
export const USER_LOAD_FALS = "USER_LOAD_FALS"

export const USER_LOGOUT = "USER_LOGOUT"
